version: '3.9'
services:
  wgportal:
    image: wgportal/wg-portal:master@sha256:e5ad4cd4a2f451fa810215f0bd9f0434ad335735881fdbfcdeaa60ea99413d51
    hostname: wgportal
    container_name: wgportal__wgportal
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    network_mode: "host"

    volumes:
      - type: bind
        source: /etc/wireguard
        target: /etc/wireguard

      - type: volume
        source: wgportal_data
        target: /app/data

      - type: bind
        source: ./config.yml
        target: /etc/config.yml
        read_only: true

    environment:
      WG_PORTAL_CONFIG: /etc/config.yml
     
    deploy:
      resources:
        limits:
          memory: 512m


  cloudflared:
    image: cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    hostname: cloudflared
    container_name: wgportal__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    network_mode: "host"

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  wgportal_data:
    name: wgportal__wgportal_data
