version: '3.9'
services:
  wgportal:
    image: wgportal/wg-portal:master@sha256:9a94a5bc2f37cdf20a340b6fd00562d93009c641ecd223c775bcccc5cf05de41
    hostname: wgportal
    container_name: wgportal__wgportal
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    network_mode: "host"

    volumes:
      - type: bind
        source: /etc/wireguard
        target: /etc/wireguard

      - type: volume
        source: wgportal_data
        target: /app/data

      - type: bind
        source: ./config.yml
        target: /etc/config.yml
        read_only: true

    environment:
      WG_PORTAL_CONFIG: /etc/config.yml
     
    deploy:
      resources:
        limits:
          memory: 512m


  cloudflared:
    image: cloudflare/cloudflared:2026.7.3@sha256:e39ee8da81ad5e05d77f38d2f51c60ca51bf2a8450ac3abab50c17fdb91d91bf
    hostname: cloudflared
    container_name: wgportal__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    network_mode: "host"

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  wgportal_data:
    name: wgportal__wgportal_data
