version: '3.9'
services:
  wgportal:
    image: wgportal/wg-portal:master@sha256:135c3a9638abc10db69317da0abffe20e3d39354b9b7e9b751be3c1fa6978229
    hostname: wgportal
    container_name: wgportal__wgportal
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    network_mode: "host"

    volumes:
      - type: bind
        source: /etc/wireguard
        target: /etc/wireguard

      - type: volume
        source: wgportal_data
        target: /app/data

      - type: bind
        source: ./config.yml
        target: /etc/config.yml
        read_only: true

    environment:
      WG_PORTAL_CONFIG: /etc/config.yml
     
    deploy:
      resources:
        limits:
          memory: 512m


  cloudflared:
    image: cloudflare/cloudflared:2026.8.2@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    hostname: cloudflared
    container_name: wgportal__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    network_mode: "host"

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  wgportal_data:
    name: wgportal__wgportal_data
